#lang racket

(require "datalog.rkt")
(require "naive.rkt")
(require "semi-naive.rkt")
(require "incremental.rkt")
(require "test.rkt")

(define r1 (:- #(Reachable x y)    #(Link x y)))
(define r2 (:- #(Reachable x y)    #(Link x z) #(Reachable z y)))
(define r3 (:- #(Node x)          #(Link x y)))
(define r4 (:- #(Node y)          #(Link x y)))

; REMOVE WORKLOAD

(define P (set r1 r2 r3 r4))
(define E (set))
(define deltas (list
  (add-tuple #(Link 'a 'b))
  (add-tuple #(Link 'b 'c))
  (add-tuple #(Link 'c 'c))
  (add-tuple #(Link 'c 'd))
  (add-tuple #(Link 'd 'e))
  (add-tuple #(Link 'e 'f))
  (remove-tuple #(Link 'e 'f))
  (add-tuple #(Link 'f 'g))
  (add-tuple #(Link 'g 'h))
  (add-tuple #(Link 'h 'i))
  (add-tuple #(Link 'm 'n))
  (add-tuple #(Link 'l 'm))
  (remove-tuple #(Link 'f 'g))
  (remove-tuple #(Link 'b 'c))
  (add-tuple #(Link 'k 'l))
  (add-tuple #(Link 'j 'k))
  (add-tuple #(Link 'k 'k))
  (add-tuple #(Link 'i 'j))
  (add-tuple #(Link 'o 'p))
  (remove-tuple #(Link 'h 'i))
  (add-tuple #(Link 'q 'r))
  (add-tuple #(Link 'p 'q))
  (remove-tuple #(Link 'j 'k))
  (remove-tuple #(Link 'k 'l))
  (add-tuple #(Link 's 'u))
  (add-tuple #(Link 's 't))
  (add-tuple #(Link 't 'u))
  (remove-tuple #(Link 'a 'b))
  (add-tuple #(Link 'v 'w))
  (remove-tuple #(Link 'p 'q))
  (remove-tuple #(Link 'o 'p))
  (add-tuple #(Link 'v 'x))
  (remove-tuple #(Link 'k 'k))
  (remove-tuple #(Link 's 'u))
  (remove-tuple #(Link 'm 'n))
  (remove-tuple #(Link 'l 'm))
  (add-tuple #(Link 'w 'x))
  (remove-tuple #(Link 'c 'd))
  (add-tuple #(Link 'y 'y))
  (remove-tuple #(Link 's 't))
  (remove-tuple #(Link 'g 'h))
  (add-tuple #(Link 'y 'x))
  (remove-tuple #(Link 'i 'j))
  (add-tuple #(Link 'y 'z))
  (remove-tuple #(Link 'c 'c))
  (remove-tuple #(Link 't 'u))
  (add-tuple #(Link 'z 'a))
  (remove-tuple #(Link 'q 'r))
  (remove-tuple #(Link 'd 'e))
  (remove-tuple #(Link 'v 'w))
  (remove-tuple #(Link 'v 'x))
  (remove-tuple #(Link 'w 'x))
  (remove-tuple #(Link 'y 'y))
  (remove-tuple #(Link 'y 'x))
  (remove-tuple #(Link 'y 'z))
  (remove-tuple #(Link 'z 'a))
))

(correctness-test P E (list solve-naive solve-semi-naive solve-incremental) deltas)
(performance-test P E (list solve-naive solve-semi-naive solve-incremental) deltas)
