#lang racket

(require "datalog.rkt")
(require "naive.rkt")
(require "semi-naive.rkt")
(require "incremental.rkt")
(require "test.rkt")

(define r1 (:- #(Reachable x y)    #(Link x y)))
(define r2 (:- #(Reachable x y)    #(Link x z) #(Reachable z y)))

; REMOVE WORKLOAD

(define P (set r1 r2))
(define E (set #(Link 'a 'b) #(Link 'b 'c) #(Link 'c 'c) #(Link 'c 'd) #(Link 'd 'e) #(Link 'e 'f) #(Link 'f 'g) #(Link 'g 'h) #(Link 'h 'i)
  #(Link 'm 'n) #(Link 'l 'm) #(Link 'k 'l) #(Link 'j 'k) #(Link 'i 'j) #(Link 'o 'p) #(Link 'q 'r) #(Link 'p 'q) #(Link 's 'u) #(Link 's 't)
  #(Link 't 'u) #(Link 'v 'w) #(Link 'v 'x) #(Link 'w 'x) #(Link 'y 'y) #(Link 'y 'x)  #(Link 'y 'z) #(Link 'z 'a)))
(define deltas (list
  (remove-tuple #(Link 'd 'e))
  (remove-tuple #(Link 'e 'f))
  (remove-tuple #(Link 'f 'g))
  (remove-tuple #(Link 'g 'h))
  (remove-tuple #(Link 'h 'i))
  (remove-tuple #(Link 'm 'n))
  (remove-tuple #(Link 'l 'm))
  (remove-tuple #(Link 'k 'l))
  (remove-tuple #(Link 'j 'k))
  (remove-tuple #(Link 'i 'j))
  (remove-tuple #(Link 'o 'p))
  (remove-tuple #(Link 'q 'r))
  (remove-tuple #(Link 'p 'q))
  (remove-tuple #(Link 's 'u))
  (remove-tuple #(Link 's 't))
  (remove-tuple #(Link 't 'u))
  (remove-tuple #(Link 'v 'w))
  (remove-tuple #(Link 'v 'x))
  (remove-tuple #(Link 'w 'x))
  (remove-tuple #(Link 'y 'y))
  (remove-tuple #(Link 'y 'x))
  (remove-tuple #(Link 'y 'z))
  (remove-tuple #(Link 'z 'a))
  (remove-tuple #(Link 'a 'b))
  (remove-tuple #(Link 'b 'c))
  (remove-tuple #(Link 'c 'c))
  (remove-tuple #(Link 'c 'd))
))

(correctness-test P E (list solve-naive solve-semi-naive solve-incremental) deltas)
(performance-test P E (list solve-naive solve-semi-naive solve-incremental) deltas)
